-- Generated by nwg-displays on 2026-07-07 at 12:30:53. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
