-- Generated by nwg-displays on 2026-06-16 at 17:20:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
