color0 #262b2c
color1 #fd4663
color2 #9eabad
color3 #9aa3aa
color4 #9a9faa
color5 #bac3c5
color6 #bac0c5
color7 #f2f2f3
color8 #626b6c
color9 #fd4663
color10 #9eabad
color11 #9aa3aa
color12 #9a9faa
color13 #bac3c5
color14 #bac0c5
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c2021
background            #1c2021
foreground            #f2f2f3
selection_foreground  #b0b4b5
selection_background  #262b2c
active_border_color   #9eabad
inactive_border_color #262b2c
url_color             #9eabad

active_tab_foreground   #1b1f20
active_tab_background   #9eabad
inactive_tab_foreground #b0b4b5
inactive_tab_background #262b2c
cursor_trail_color      #b0b4b5
